// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

var vertexShaderSource = "\nattribute vec2 a_position;\n\nvoid main() {\n  gl_Position = vec4(a_position, 0.0, 1.0);\n}\n";

var fragmentShaderSource = "\nprecision mediump float;\n\nvoid main() {\n  gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);\n}\n";

function initWebGL() {
  var canvasElement = document.getElementById("canvas");
  if (canvasElement == null) {
    console.log("Canvas element not found");
    return ;
  }
  var gl = getContext(canvasElement, "WebGL", {
        alpha: true,
        depth: true,
        stencil: false,
        antialias: true,
        premultipliedAlpha: true,
        preserveDrawingBuffer: false,
        preferLowPowerToHighPerformance: false,
        failIfMajorPerformanceCaveat: false
      });
  if (gl !== undefined) {
    var gl$1 = Caml_option.valFromOption(gl);
    var vertexShader = gl$1.createShader(35633);
    if (vertexShader !== undefined) {
      var vertexShader$1 = Caml_option.valFromOption(vertexShader);
      gl$1.shaderSource(vertexShader$1, vertexShaderSource);
      gl$1.compileShader(vertexShader$1);
      var fragmentShader = gl$1.createShader(35632);
      if (fragmentShader !== undefined) {
        var fragmentShader$1 = Caml_option.valFromOption(fragmentShader);
        gl$1.shaderSource(fragmentShader$1, fragmentShaderSource);
        gl$1.compileShader(fragmentShader$1);
        var program = gl$1.createProgram();
        if (program !== undefined) {
          var program$1 = Caml_option.valFromOption(program);
          gl$1.attachShader(program$1, vertexShader$1);
          gl$1.attachShader(program$1, fragmentShader$1);
          gl$1.linkProgram(program$1);
          gl$1.useProgram(program$1);
          console.log("MngWebGL initialized successfully");
          return ;
        }
        console.log("Failed to create program");
        return ;
      }
      console.log("Failed to create fragment shader");
      return ;
    }
    console.log("Failed to create vertex shader");
    return ;
  }
  console.log("Failed to get MngWebGL context");
}

export {
  vertexShaderSource ,
  fragmentShaderSource ,
  initWebGL ,
}
/* No side effect */
