// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function getContextWithOptionalOptions(canvasElement, contextType, alpha, depth, stencil, antialias, premultipliedAlpha, preserveDrawingBuffer, preferLowPowerToHighPerformance, failIfMajorPerformanceCaveat) {
  if (alpha === undefined && depth === undefined && stencil === undefined && antialias === undefined && premultipliedAlpha === undefined && preserveDrawingBuffer === undefined && preferLowPowerToHighPerformance === undefined && failIfMajorPerformanceCaveat === undefined) {
    return getContext(canvasElement, contextType);
  }
  var attributes_alpha = Core__Option.getOr(alpha, true);
  var attributes_depth = Core__Option.getOr(depth, true);
  var attributes_stencil = Core__Option.getOr(stencil, false);
  var attributes_antialias = Core__Option.getOr(antialias, true);
  var attributes_premultipliedAlpha = Core__Option.getOr(premultipliedAlpha, true);
  var attributes_preserveDrawingBuffer = Core__Option.getOr(preserveDrawingBuffer, false);
  var attributes_preferLowPowerToHighPerformance = Core__Option.getOr(preferLowPowerToHighPerformance, false);
  var attributes_failIfMajorPerformanceCaveat = Core__Option.getOr(failIfMajorPerformanceCaveat, false);
  var attributes = {
    alpha: attributes_alpha,
    depth: attributes_depth,
    stencil: attributes_stencil,
    antialias: attributes_antialias,
    premultipliedAlpha: attributes_premultipliedAlpha,
    preserveDrawingBuffer: attributes_preserveDrawingBuffer,
    preferLowPowerToHighPerformance: attributes_preferLowPowerToHighPerformance,
    failIfMajorPerformanceCaveat: attributes_failIfMajorPerformanceCaveat
  };
  return getContext(canvasElement, contextType, attributes);
}

function isInvalidAttribLocation(loc) {
  return loc < 0;
}

var Types;

var Constants;

export {
  Types ,
  Constants ,
  getContextWithOptionalOptions ,
  isInvalidAttribLocation ,
}
/* No side effect */
