// Generated by ReScript, PLEASE EDIT WITH CARE


function isInvalidAttribLocation(loc) {
  return loc < 0;
}

var Types;

var Constants;

export {
  Types ,
  Constants ,
  isInvalidAttribLocation ,
}
/* No side effect */
